version = 1
SPDX-PackageName = "btp-fiori-tools"
SPDX-PackageSupplier = "Regina Sheynblat (regina.sheynblat@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/SAP-docs/btp-fiori-tools"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and SAP-docs/btp-fiori-tools contributors"
SPDX-License-Identifier = "CC-BY-4.0"
